-- ============================================================
-- Projeto : Power BI Finance Dashboard
-- Arquivo : 02_create_tables.sql
-- Banco   : Oracle Autonomous AI Database
-- Schema  : FINANCE
-- Modelo  : Dimensional / Star Schema
-- ============================================================


-- ============================================================
-- 1. DIMENSÃO CALENDÁRIO
-- ============================================================

CREATE TABLE DIM_CALENDARIO
(
    SK_DATA              NUMBER(8)       NOT NULL,
    DATA                 DATE            NOT NULL,
    ANO                  NUMBER(4)       NOT NULL,
    MES                  NUMBER(2)       NOT NULL,
    NOME_MES             VARCHAR2(20)    NOT NULL,
    ANO_MES              VARCHAR2(7)     NOT NULL,
    TRIMESTRE            NUMBER(1)       NOT NULL,
    NOME_TRIMESTRE       VARCHAR2(10),
    DIA                  NUMBER(2)       NOT NULL,
    DIA_SEMANA           NUMBER(1),
    NOME_DIA_SEMANA      VARCHAR2(20),
    SEMANA_ANO           NUMBER(2),
    EH_FIM_SEMANA        CHAR(1),
    EH_DIA_UTIL          CHAR(1),

    CONSTRAINT PK_DIM_CALENDARIO
        PRIMARY KEY (SK_DATA),

    CONSTRAINT UK_DIM_CALENDARIO_DATA
        UNIQUE (DATA),

    CONSTRAINT CK_CAL_FIM_SEMANA
        CHECK (EH_FIM_SEMANA IN ('S','N')),

    CONSTRAINT CK_CAL_DIA_UTIL
        CHECK (EH_DIA_UTIL IN ('S','N'))
);


-- ============================================================
-- 2. DIMENSÃO CATEGORIA
-- ============================================================

CREATE TABLE DIM_CATEGORIA
(
    SK_CATEGORIA         NUMBER GENERATED BY DEFAULT AS IDENTITY,
    CATEGORIA            VARCHAR2(100)   NOT NULL,
    SUBCATEGORIA         VARCHAR2(100),
    GRUPO                 VARCHAR2(100),
    ATIVO                 CHAR(1) DEFAULT 'S' NOT NULL,

    CONSTRAINT PK_DIM_CATEGORIA
        PRIMARY KEY (SK_CATEGORIA),

    CONSTRAINT CK_CATEGORIA_ATIVO
        CHECK (ATIVO IN ('S','N'))
);


-- ============================================================
-- 3. DIMENSÃO CONTA
-- Conta corrente, carteira, investimento etc.
-- ============================================================

CREATE TABLE DIM_CONTA
(
    SK_CONTA             NUMBER GENERATED BY DEFAULT AS IDENTITY,
    NOME_CONTA           VARCHAR2(100)   NOT NULL,
    INSTITUICAO          VARCHAR2(100),
    TIPO_CONTA           VARCHAR2(50),
    ATIVO                CHAR(1) DEFAULT 'S' NOT NULL,

    CONSTRAINT PK_DIM_CONTA
        PRIMARY KEY (SK_CONTA),

    CONSTRAINT CK_CONTA_ATIVO
        CHECK (ATIVO IN ('S','N'))
);


-- ============================================================
-- 4. DIMENSÃO CARTÃO
-- ============================================================

CREATE TABLE DIM_CARTAO
(
    SK_CARTAO                    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    NOME_CARTAO                  VARCHAR2(100) NOT NULL,
    BANDEIRA                     VARCHAR2(30),
    EMISSOR                      VARCHAR2(100),

    DIA_FECHAMENTO               NUMBER(2),
    DIA_VENCIMENTO               NUMBER(2),
    MELHOR_DIA_COMPRA            NUMBER(2),

    LIMITE_COMPRA                NUMBER(15,2),
    LIMITE_SAQUE                 NUMBER(15,2),

    ATIVO                        CHAR(1) DEFAULT 'S' NOT NULL,

    CONSTRAINT PK_DIM_CARTAO
        PRIMARY KEY (SK_CARTAO),

    CONSTRAINT UK_DIM_CARTAO_NOME
        UNIQUE (NOME_CARTAO),

    CONSTRAINT CK_CARTAO_ATIVO
        CHECK (ATIVO IN ('S','N')),

    CONSTRAINT CK_CARTAO_FECHAMENTO
        CHECK (
            DIA_FECHAMENTO IS NULL
            OR DIA_FECHAMENTO BETWEEN 1 AND 31
        ),

    CONSTRAINT CK_CARTAO_VENCIMENTO
        CHECK (
            DIA_VENCIMENTO IS NULL
            OR DIA_VENCIMENTO BETWEEN 1 AND 31
        ),

    CONSTRAINT CK_CARTAO_MELHOR_DIA
        CHECK (
            MELHOR_DIA_COMPRA IS NULL
            OR MELHOR_DIA_COMPRA BETWEEN 1 AND 31
        )
);


-- ============================================================
-- 5. DIMENSÃO TIPO DE MOVIMENTO
-- ============================================================

CREATE TABLE DIM_TIPO_MOVIMENTO
(
    SK_TIPO_MOVIMENTO    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    FLUXO                VARCHAR2(10)    NOT NULL,
    TIPO                 VARCHAR2(20),
    DESCRICAO            VARCHAR2(100),

    CONSTRAINT PK_DIM_TIPO_MOVIMENTO
        PRIMARY KEY (SK_TIPO_MOVIMENTO),

    CONSTRAINT CK_TIPO_MOV_FLUXO
        CHECK (FLUXO IN ('ENTRADA','SAIDA')),

    CONSTRAINT CK_TIPO_MOV_TIPO
        CHECK (
            TIPO IS NULL
            OR TIPO IN ('FIXA','VARIAVEL')
        )
);


-- ============================================================
-- 6. FATO MOVIMENTO FINANCEIRO
-- Uma linha = um lançamento financeiro
-- ============================================================

CREATE TABLE FATO_MOVIMENTO_FINANCEIRO
(
    SK_MOVIMENTO          NUMBER GENERATED BY DEFAULT AS IDENTITY,

    SK_DATA               NUMBER(8)      NOT NULL,
    SK_CONTA              NUMBER,
    SK_CATEGORIA          NUMBER,
    SK_TIPO_MOVIMENTO     NUMBER         NOT NULL,

    DESCRICAO             VARCHAR2(300)  NOT NULL,
    VALOR                 NUMBER(15,2)   NOT NULL,

    DATA_VIGENCIA         DATE,
    OBSERVACAO            VARCHAR2(500),

    DATA_CARGA            TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_FATO_MOV_FIN
        PRIMARY KEY (SK_MOVIMENTO),

    CONSTRAINT FK_MOV_DATA
        FOREIGN KEY (SK_DATA)
        REFERENCES DIM_CALENDARIO(SK_DATA),

    CONSTRAINT FK_MOV_CONTA
        FOREIGN KEY (SK_CONTA)
        REFERENCES DIM_CONTA(SK_CONTA),

    CONSTRAINT FK_MOV_CATEGORIA
        FOREIGN KEY (SK_CATEGORIA)
        REFERENCES DIM_CATEGORIA(SK_CATEGORIA),

    CONSTRAINT FK_MOV_TIPO
        FOREIGN KEY (SK_TIPO_MOVIMENTO)
        REFERENCES DIM_TIPO_MOVIMENTO(SK_TIPO_MOVIMENTO),

    CONSTRAINT CK_MOV_VALOR
        CHECK (VALOR >= 0)
);


-- ============================================================
-- 7. FATO CARTÃO DE CRÉDITO
-- Uma linha = uma compra/parcela lançada
-- ============================================================

CREATE TABLE FATO_CARTAO_CREDITO
(
    SK_COMPRA_CARTAO      NUMBER GENERATED BY DEFAULT AS IDENTITY,

    SK_DATA_COMPRA        NUMBER(8)      NOT NULL,
    SK_DATA_VENCIMENTO    NUMBER(8),
    SK_CARTAO             NUMBER         NOT NULL,
    SK_CATEGORIA          NUMBER,

    DESCRICAO             VARCHAR2(300)  NOT NULL,

    VALOR_TOTAL_COMPRA    NUMBER(15,2)   NOT NULL,
    VALOR_PARCELA         NUMBER(15,2),

    TIPO_COMPRA           VARCHAR2(15)   NOT NULL,

    NUMERO_PARCELA        NUMBER(3),
    TOTAL_PARCELAS        NUMBER(3),

    DATA_CARGA            TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_FATO_CARTAO
        PRIMARY KEY (SK_COMPRA_CARTAO),

    CONSTRAINT FK_CARTAO_DATA_COMPRA
        FOREIGN KEY (SK_DATA_COMPRA)
        REFERENCES DIM_CALENDARIO(SK_DATA),

    CONSTRAINT FK_CARTAO_DATA_VENC
        FOREIGN KEY (SK_DATA_VENCIMENTO)
        REFERENCES DIM_CALENDARIO(SK_DATA),

    CONSTRAINT FK_CARTAO_DIM
        FOREIGN KEY (SK_CARTAO)
        REFERENCES DIM_CARTAO(SK_CARTAO),

    CONSTRAINT FK_CARTAO_CATEGORIA
        FOREIGN KEY (SK_CATEGORIA)
        REFERENCES DIM_CATEGORIA(SK_CATEGORIA),

    CONSTRAINT CK_CARTAO_TIPO_COMPRA
        CHECK (
            TIPO_COMPRA IN ('INTEGRAL','PARCELADA')
        ),

    CONSTRAINT CK_CARTAO_VALOR
        CHECK (VALOR_TOTAL_COMPRA >= 0),

    CONSTRAINT CK_CARTAO_PARCELAS
        CHECK (
            TOTAL_PARCELAS IS NULL
            OR TOTAL_PARCELAS >= 1
        )
);


-- ============================================================
-- 8. FATO EMPRÉSTIMO
-- ============================================================

CREATE TABLE FATO_EMPRESTIMO
(
    SK_EMPRESTIMO         NUMBER GENERATED BY DEFAULT AS IDENTITY,

    SK_DATA_CONTRATACAO   NUMBER(8)       NOT NULL,
    SK_CONTA              NUMBER,

    DESCRICAO             VARCHAR2(300)   NOT NULL,

    VALOR_CONTRATADO      NUMBER(15,2)    NOT NULL,
    VALOR_PARCELA         NUMBER(15,2),

    QUANTIDADE_PARCELAS   NUMBER(4),
    PARCELAS_PAGAS        NUMBER(4) DEFAULT 0,

    TAXA_JUROS_MENSAL     NUMBER(9,6),
    TAXA_JUROS_ANUAL      NUMBER(9,6),

    STATUS                VARCHAR2(20) DEFAULT 'ATIVO' NOT NULL,

    DATA_CARGA            TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_FATO_EMPRESTIMO
        PRIMARY KEY (SK_EMPRESTIMO),

    CONSTRAINT FK_EMPRESTIMO_DATA
        FOREIGN KEY (SK_DATA_CONTRATACAO)
        REFERENCES DIM_CALENDARIO(SK_DATA),

    CONSTRAINT FK_EMPRESTIMO_CONTA
        FOREIGN KEY (SK_CONTA)
        REFERENCES DIM_CONTA(SK_CONTA),

    CONSTRAINT CK_EMPRESTIMO_STATUS
        CHECK (
            STATUS IN (
                'ATIVO',
                'QUITADO',
                'ATRASADO',
                'CANCELADO'
            )
        ),

    CONSTRAINT CK_EMPRESTIMO_VALOR
        CHECK (VALOR_CONTRATADO >= 0)
);
