-- ============================================================
-- Projeto : Power BI Finance Dashboard
-- Arquivo : 03_create_fact_tables.sql
-- Schema  : FINANCE
-- Objetivo: Criação das tabelas fato
-- ============================================================


-- ============================================================
-- 1. FATO_MOVIMENTO_FINANCEIRO
--
-- Grão:
-- Uma linha representa um lançamento financeiro individual.
-- ============================================================

CREATE TABLE FATO_MOVIMENTO_FINANCEIRO
(
    SK_MOVIMENTO          NUMBER GENERATED BY DEFAULT AS IDENTITY
                           NOT NULL,

    SK_DATA               NUMBER(8)
                           NOT NULL,

    SK_CONTA              NUMBER,

    SK_CATEGORIA          NUMBER,

    SK_TIPO_MOVIMENTO     NUMBER
                           NOT NULL,

    DESCRICAO             VARCHAR2(300)
                           NOT NULL,

    VALOR                 NUMBER(15,2)
                           NOT NULL,

    DATA_VIGENCIA         DATE,

    OBSERVACAO            VARCHAR2(500),

    DATA_CARGA            TIMESTAMP
                           DEFAULT SYSTIMESTAMP
                           NOT NULL,

    CONSTRAINT PK_FATO_MOV_FIN
        PRIMARY KEY (SK_MOVIMENTO),

    CONSTRAINT FK_MOV_DATA
        FOREIGN KEY (SK_DATA)
        REFERENCES DIM_CALENDARIO (SK_DATA),

    CONSTRAINT FK_MOV_CONTA
        FOREIGN KEY (SK_CONTA)
        REFERENCES DIM_CONTA (SK_CONTA),

    CONSTRAINT FK_MOV_CATEGORIA
        FOREIGN KEY (SK_CATEGORIA)
        REFERENCES DIM_CATEGORIA (SK_CATEGORIA),

    CONSTRAINT FK_MOV_TIPO
        FOREIGN KEY (SK_TIPO_MOVIMENTO)
        REFERENCES DIM_TIPO_MOVIMENTO (SK_TIPO_MOVIMENTO),

    CONSTRAINT CK_MOV_VALOR
        CHECK (VALOR >= 0)
);


-- ============================================================
-- 2. FATO_CARTAO_CREDITO
--
-- Grão:
-- Uma linha representa uma compra/parcela de cartão.
-- ============================================================

CREATE TABLE FATO_CARTAO_CREDITO
(
    SK_COMPRA_CARTAO      NUMBER GENERATED BY DEFAULT AS IDENTITY
                           NOT NULL,

    SK_DATA_COMPRA        NUMBER(8)
                           NOT NULL,

    SK_DATA_VENCIMENTO    NUMBER(8),

    SK_CARTAO             NUMBER
                           NOT NULL,

    SK_CATEGORIA          NUMBER,

    DESCRICAO             VARCHAR2(300)
                           NOT NULL,

    VALOR_TOTAL_COMPRA    NUMBER(15,2)
                           NOT NULL,

    VALOR_PARCELA         NUMBER(15,2),

    TIPO_COMPRA           VARCHAR2(15)
                           NOT NULL,

    NUMERO_PARCELA        NUMBER(3),

    TOTAL_PARCELAS        NUMBER(3),

    DATA_CARGA            TIMESTAMP
                           DEFAULT SYSTIMESTAMP
                           NOT NULL,

    CONSTRAINT PK_FATO_CARTAO
        PRIMARY KEY (SK_COMPRA_CARTAO),

    CONSTRAINT FK_CARTAO_DATA_COMPRA
        FOREIGN KEY (SK_DATA_COMPRA)
        REFERENCES DIM_CALENDARIO (SK_DATA),

    CONSTRAINT FK_CARTAO_DATA_VENC
        FOREIGN KEY (SK_DATA_VENCIMENTO)
        REFERENCES DIM_CALENDARIO (SK_DATA),

    CONSTRAINT FK_CARTAO_DIM
        FOREIGN KEY (SK_CARTAO)
        REFERENCES DIM_CARTAO (SK_CARTAO),

    CONSTRAINT FK_CARTAO_CATEGORIA
        FOREIGN KEY (SK_CATEGORIA)
        REFERENCES DIM_CATEGORIA (SK_CATEGORIA),

    CONSTRAINT CK_CARTAO_TIPO_COMPRA
        CHECK (TIPO_COMPRA IN ('INTEGRAL', 'PARCELADA')),

    CONSTRAINT CK_CARTAO_VALOR
        CHECK (VALOR_TOTAL_COMPRA >= 0),

    CONSTRAINT CK_CARTAO_VALOR_PARCELA
        CHECK (
            VALOR_PARCELA IS NULL
            OR VALOR_PARCELA >= 0
        ),

    CONSTRAINT CK_CARTAO_NUM_PARCELA
        CHECK (
            NUMERO_PARCELA IS NULL
            OR NUMERO_PARCELA >= 1
        ),

    CONSTRAINT CK_CARTAO_TOTAL_PARCELAS
        CHECK (
            TOTAL_PARCELAS IS NULL
            OR TOTAL_PARCELAS >= 1
        )
);


-- ============================================================
-- 3. FATO_EMPRESTIMO
--
-- Grão:
-- Uma linha representa um contrato de empréstimo.
-- ============================================================

CREATE TABLE FATO_EMPRESTIMO
(
    SK_EMPRESTIMO         NUMBER GENERATED BY DEFAULT AS IDENTITY
                           NOT NULL,

    SK_DATA_CONTRATACAO   NUMBER(8)
                           NOT NULL,

    SK_CONTA              NUMBER,

    DESCRICAO             VARCHAR2(300)
                           NOT NULL,

    VALOR_CONTRATADO      NUMBER(15,2)
                           NOT NULL,

    VALOR_PARCELA         NUMBER(15,2),

    QUANTIDADE_PARCELAS   NUMBER(4),

    PARCELAS_PAGAS        NUMBER(4)
                           DEFAULT 0,

    TAXA_JUROS_MENSAL     NUMBER(9,6),

    TAXA_JUROS_ANUAL      NUMBER(9,6),

    STATUS                VARCHAR2(20)
                           DEFAULT 'ATIVO'
                           NOT NULL,

    DATA_CARGA            TIMESTAMP
                           DEFAULT SYSTIMESTAMP
                           NOT NULL,

    CONSTRAINT PK_FATO_EMPRESTIMO
        PRIMARY KEY (SK_EMPRESTIMO),

    CONSTRAINT FK_EMPRESTIMO_DATA
        FOREIGN KEY (SK_DATA_CONTRATACAO)
        REFERENCES DIM_CALENDARIO (SK_DATA),

    CONSTRAINT FK_EMPRESTIMO_CONTA
        FOREIGN KEY (SK_CONTA)
        REFERENCES DIM_CONTA (SK_CONTA),

    CONSTRAINT CK_EMPRESTIMO_STATUS
        CHECK (
            STATUS IN (
                'ATIVO',
                'QUITADO',
                'ATRASADO',
                'CANCELADO'
            )
        ),

    CONSTRAINT CK_EMPRESTIMO_VALOR
        CHECK (VALOR_CONTRATADO >= 0),

    CONSTRAINT CK_EMPRESTIMO_PARCELA
        CHECK (
            VALOR_PARCELA IS NULL
            OR VALOR_PARCELA >= 0
        ),

    CONSTRAINT CK_EMPRESTIMO_QTD_PARCELAS
        CHECK (
            QUANTIDADE_PARCELAS IS NULL
            OR QUANTIDADE_PARCELAS >= 1
        ),

    CONSTRAINT CK_EMPRESTIMO_PAGAS
        CHECK (
            PARCELAS_PAGAS >= 0
        )
);
