-- ============================================================
-- Projeto : Power BI Finance Dashboard
-- Arquivo : 07_create_views.sql
-- Schema  : FINANCE
-- Objetivo: Criar views analíticas para consumo no Power BI
-- ============================================================


-- ============================================================
-- 1. VW_MOVIMENTO_FINANCEIRO
-- ============================================================

CREATE OR REPLACE VIEW VW_MOVIMENTO_FINANCEIRO AS
SELECT
    F.SK_MOVIMENTO,

    C.SK_DATA,
    C.DATA,
    C.ANO,
    C.MES,
    C.NOME_MES,
    C.ANO_MES,
    C.TRIMESTRE,
    C.NOME_TRIMESTRE,
    C.DIA,
    C.DIA_SEMANA,
    C.NOME_DIA_SEMANA,
    C.SEMANA_ANO,
    C.EH_FIM_SEMANA,
    C.EH_DIA_UTIL,

    CO.SK_CONTA,
    CO.NOME_CONTA,
    CO.INSTITUICAO,
    CO.TIPO_CONTA,

    CAT.SK_CATEGORIA,
    CAT.CATEGORIA,
    CAT.SUBCATEGORIA,
    CAT.GRUPO,

    TM.SK_TIPO_MOVIMENTO,
    TM.FLUXO,
    TM.TIPO,
    TM.DESCRICAO AS DESCRICAO_TIPO_MOVIMENTO,

    F.DESCRICAO AS DESCRICAO_MOVIMENTO,
    F.VALOR,
    F.DATA_VIGENCIA,
    F.OBSERVACAO,
    F.DATA_CARGA

FROM FATO_MOVIMENTO_FINANCEIRO F

INNER JOIN DIM_CALENDARIO C
    ON C.SK_DATA = F.SK_DATA

LEFT JOIN DIM_CONTA CO
    ON CO.SK_CONTA = F.SK_CONTA

LEFT JOIN DIM_CATEGORIA CAT
    ON CAT.SK_CATEGORIA = F.SK_CATEGORIA

-- ============================================================
-- 2. VW_CARTAO_CREDITO
-- ============================================================

CREATE OR REPLACE VIEW VW_CARTAO_CREDITO AS
SELECT
    F.SK_COMPRA_CARTAO,

    DC.SK_DATA AS SK_DATA_COMPRA,
    DC.DATA AS DATA_COMPRA,
    DC.ANO AS ANO_COMPRA,
    DC.MES AS MES_COMPRA,
    DC.NOME_MES AS NOME_MES_COMPRA,
    DC.ANO_MES AS ANO_MES_COMPRA,

    DV.SK_DATA AS SK_DATA_VENCIMENTO,
    DV.DATA AS DATA_VENCIMENTO,
    DV.ANO AS ANO_VENCIMENTO,
    DV.MES AS MES_VENCIMENTO,
    DV.NOME_MES AS NOME_MES_VENCIMENTO,
    DV.ANO_MES AS ANO_MES_VENCIMENTO,

    CA.SK_CARTAO,
    CA.NOME_CARTAO,
    CA.BANDEIRA,
    CA.EMISSOR,
    CA.DIA_FECHAMENTO,
    CA.DIA_VENCIMENTO,
    CA.MELHOR_DIA_COMPRA,
    CA.LIMITE_COMPRA,
    CA.LIMITE_SAQUE,

    CAT.SK_CATEGORIA,
    CAT.CATEGORIA,
    CAT.SUBCATEGORIA,
    CAT.GRUPO,

    F.DESCRICAO,
    F.VALOR_TOTAL_COMPRA,
    F.VALOR_PARCELA,
    F.TIPO_COMPRA,
    F.NUMERO_PARCELA,
    F.TOTAL_PARCELAS,
    F.DATA_CARGA

FROM FATO_CARTAO_CREDITO F

INNER JOIN DIM_CALENDARIO DC
    ON DC.SK_DATA = F.SK_DATA_COMPRA

LEFT JOIN DIM_CALENDARIO DV
    ON DV.SK_DATA = F.SK_DATA_VENCIMENTO

INNER JOIN DIM_CARTAO CA
    ON CA.SK_CARTAO = F.SK_CARTAO

LEFT JOIN DIM_CATEGORIA CAT
    ON CAT.SK_CATEGORIA = F.SK_CATEGORIA;

INNER JOIN DIM_TIPO_MOVIMENTO TM
    ON TM.SK_TIPO_MOVIMENTO = F.SK_TIPO_MOVIMENTO;

-- ============================================================
-- 3. VW_EMPRESTIMOS
-- ============================================================

CREATE OR REPLACE VIEW VW_EMPRESTIMOS AS
SELECT
    F.SK_EMPRESTIMO,

    C.SK_DATA AS SK_DATA_CONTRATACAO,
    C.DATA AS DATA_CONTRATACAO,
    C.ANO AS ANO_CONTRATACAO,
    C.MES AS MES_CONTRATACAO,
    C.NOME_MES AS NOME_MES_CONTRATACAO,
    C.ANO_MES AS ANO_MES_CONTRATACAO,

    CO.SK_CONTA,
    CO.NOME_CONTA,
    CO.INSTITUICAO,
    CO.TIPO_CONTA,

    F.DESCRICAO,
    F.VALOR_CONTRATADO,
    F.VALOR_PARCELA,
    F.QUANTIDADE_PARCELAS,
    F.PARCELAS_PAGAS,

    F.QUANTIDADE_PARCELAS
        - NVL(F.PARCELAS_PAGAS, 0)
        AS PARCELAS_RESTANTES,

    F.TAXA_JUROS_MENSAL,
    F.TAXA_JUROS_ANUAL,
    F.STATUS,
    F.DATA_CARGA

FROM FATO_EMPRESTIMO F

INNER JOIN DIM_CALENDARIO C
    ON C.SK_DATA = F.SK_DATA_CONTRATACAO

LEFT JOIN DIM_CONTA CO
    ON CO.SK_CONTA = F.SK_CONTA;

-- ============================================================
-- 4. VW_RESUMO_MENSAL
-- ============================================================

CREATE OR REPLACE VIEW VW_RESUMO_MENSAL AS
SELECT
    C.ANO,
    C.MES,
    C.NOME_MES,
    C.ANO_MES,

    SUM(
        CASE
            WHEN TM.FLUXO = 'ENTRADA'
            THEN F.VALOR
            ELSE 0
        END
    ) AS TOTAL_ENTRADAS,

    SUM(
        CASE
            WHEN TM.FLUXO = 'SAIDA'
            THEN F.VALOR
            ELSE 0
        END
    ) AS TOTAL_SAIDAS,

    SUM(
        CASE
            WHEN TM.FLUXO = 'ENTRADA'
            THEN F.VALOR
            ELSE -F.VALOR
        END
    ) AS RESULTADO_MENSAL,

    SUM(
        CASE
            WHEN TM.FLUXO = 'SAIDA'
             AND TM.TIPO = 'FIXA'
            THEN F.VALOR
            ELSE 0
        END
    ) AS DESPESAS_FIXAS,

    SUM(
        CASE
            WHEN TM.FLUXO = 'SAIDA'
             AND TM.TIPO = 'VARIAVEL'
            THEN F.VALOR
            ELSE 0
        END
    ) AS DESPESAS_VARIAVEIS

FROM FATO_MOVIMENTO_FINANCEIRO F

INNER JOIN DIM_CALENDARIO C
    ON C.SK_DATA = F.SK_DATA

INNER JOIN DIM_TIPO_MOVIMENTO TM
    ON TM.SK_TIPO_MOVIMENTO = F.SK_TIPO_MOVIMENTO

GROUP BY
    C.ANO,
    C.MES,
    C.NOME_MES,
    C.ANO_MES;


